apiVersion: v1
kind: ConfigMap
metadata:
  name: machine-sensor-1
data:
  MQTT_HOSTNAME=broker-amq-mqtt-all-0-svc-rte-manuela-tst-all.apps.{{ .Values.global.datacenter.clustername }}.{{ .Values.global.datacenter.domain }}
  MQTT_PORT={{ .Values.machineSensor1.port }}
