apiVersion: v1
kind: ConfigMap
metadata:
  name: messaging-configmap
  namespace: manuela-stormshift-messaging
data:
  VIBRATION_ALERT_ENABLED: "{{ .Values.messaging.vibrationAlert }}"
  VIBRATION_ANOMALY_ENABLED: "{{ .Values.messaging.vibrationAnomaly }}"
  NODE_TLS_REJECT_UNAUTHORIZED: "{{ .Values.messaging.nodeTlsReject }}"

