apiVersion: kfdef.apps.kubeflow.org/v1
kind: KfDef
metadata:
  finalizers:
  - kfdef-finalizer.kfdef.apps.kubeflow.org
  name: opendatahub
spec:
  applications:
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: odh-common
    name: odh-common
  - kustomizeConfig:
      overlays:
      - authentication
      repoRef:
        name: manifests
        path: odh-dashboard
    name: odh-dashboard
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: odh-notebook-controller
    name: odh-notebook-controller
  - kustomizeConfig:
      overlays:
      - odh-model-controller
      repoRef:
        name: manifests
        path: model-mesh
    name: model-mesh
  - kustomizeConfig:
      overlays:
      - metadata-store-mariadb
      - ds-pipeline-ui
      - object-store-minio
      - default-configs
      repoRef:
        name: manifests
        path: data-science-pipelines
    name: ds-pipelines
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: grafana/cluster
    name: grafana-cluster
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: grafana/grafana
    name: grafana-instance
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: prometheus/cluster
    name: prometheus-cluster
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: prometheus/operator
    name: prometheus-operator
  - kustomizeConfig:
      overlays:
      - additional
      repoRef:
        name: manifests
        path: jupyterhub/notebook-images
    name: notebook-images
  repos:
  - name: manifests
    uri: https://github.com/opendatahub-io/odh-manifests/tarball/v1.4
  version: v1.4.0
