resources:
  - argocd-operator-subs/namespace.yaml
  - argocd-operator-subs/channel.yaml
  - argocd-operator-subs/placementrule.yaml
  - argocd-operator-subs/subscription.yaml
  - manuela-central/argocd-hub-centraldatacenter.yaml

bases:
  - tekton/
  - odh-resources/

transformers:
  - site-config.yaml

