main:
  clusterGroupName: datacenter

global:
  pattern: industrial-edge

  options:
    useCSV: False
    syncPolicy: Automatic
    installPlanApproval: Automatic

  imageregistry:
    account: claudiol
    hostname: quay.io
    type: quay

  git:
    hostname: github.com
    account: claudiol
    username: claudiol
    email: claudiol@redhat.com
    dev_revision: main

  s3:
    bucket:
      name: manuela-data-lake
      region: us-west-1
      message:
        aggregation:
          count: 50
      custom:
        endpoint:
          enabled: false
