main:
  clusterGroupName: datacenter
  multiSourceConfig:
    enabled: true
    clusterGroupChartVersion: 0.9.*
  git:
    repoUpstreamURL: https://github.com/validatedpatterns/industrial-edge

global:
  pattern: industrial-edge

  options:
    useCSV: False
    syncPolicy: Automatic
    installPlanApproval: Automatic

  imageregistry:
    # account: PLAINTEXT
    # hostname: quay.io
    # type: quay
    # Account and hostname will be set automatically if the type is openshift-internal
    type: openshift-internal

  git:
    account: gitea_admin
    #username: PLAINTEXT
    email: SOMEWHERE@EXAMPLE.COM
    # Branch used for the manuela-dev repository
    dev_revision: main
