main:
  clusterGroupName: datacenter
  multiSourceConfig:
    enabled: true
    clusterGroupChartVersion: 0.9.*
  git:
    repoUpstreamURL: https://github.com/validatedpatterns/industrial-edge

# FIXME: when switching this branch to main, we need to rebuild all bootstrap containers,
# check their version and make sure we reference those in the main branch
# This container has the new API endpoint of the inference service
iot_consumer:
  bootstrap_image: quay.io/aeros/iot-consumer:0.3.2-40

global:
  pattern: industrial-edge

  options:
    useCSV: False
    syncPolicy: Automatic
    installPlanApproval: Automatic

  imageregistry:
    account: PLAINTEXT
    hostname: quay.io
    type: quay

  git:
    account: gitea_admin
    #username: PLAINTEXT
    email: SOMEWHERE@EXAMPLE.COM
    # Branch used for the manuela-dev repository
    dev_revision: integrate_rhoai

  s3:
    bucket:
      message:
        aggregation:
          count: 50
