main:
  clusterGroupName: datacenter
  multiSourceConfig:
    enabled: true
    clusterGroupChartVersion: 0.9.*
  git:
    repoUpstreamURL: https://github.com/validatedpatterns/industrial-edge

global:
  pattern: industrial-edge

  options:
    useCSV: False
    syncPolicy: Automatic
    installPlanApproval: Automatic

  imageregistry:
    account: PLAINTEXT
    hostname: quay.io
    type: quay

  git:
    account: gitea_admin
    #username: PLAINTEXT
    email: SOMEWHERE@EXAMPLE.COM
    # Branch used for the manuela-dev repository
    dev_revision: main

  s3:
    bucket:
      message:
        aggregation:
          count: 50
