apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: manuela-crc-messaging
resources:
- messaging-namespace.yaml
- messaging-operatorgroup.yaml
patchesStrategicMerge:
- route.yaml
bases:
#- github.com/sa-mw-dach/manuela-gitops/config/templates/manuela/messaging
- ../../../templates/manuela-openshift-test/messaging
- ../../../templates/manuela-team-rolebindings

images:
- name: messaging
  newName: image-registry.openshift-image-registry.svc:5000/manuela-crc-messaging/messaging
