global:
  imageregistry:
    hostname: quay.io

  git:
    hostname: github.com
    account: PLAINTEXT
    username: PLAINTEXT

secretStore:
  name: vault-backend
  kind: ClusterSecretStore

gitsecret:
  key: secret/data/hub/git

imageregistrysecret:
  key: secret/data/hub/imageregistry

s3secret:
  key: secret/data/hub/aws
