apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: seed-iot-anomaly-detection-run
spec:
  pipelineRef:
    name: iot-component
  serviceAccountName: pipeline
  timeout: 1h0m0s
  workspaces:
  - configMap:
      name: environment
    name: config
  - name: argocd-env-secret
    secret:
      secretName: argocd-env
  - name: build-artifacts
    volumeClaimTemplate:
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
  - name: gitrepos
    volumeClaimTemplate:
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 128Mi
  parameters:
  - name: component_name
    value: iot-anomaly-detection
  - name: seed_prod_with_tags
    value: true
  - name: builder_image
    value: quay.io/hybridcloudpatterns/python-38-rhel7
  - name: output_image_name
    value: anomaly-detection
  - name: target_image_configmapkey
    value: IOT_ANOMALY_IMAGE
  - name: configmap_prefix
    value: IOT_ANOMALY
