apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: anomaly-detection
spec:
  tags:
  - name: 0.3.2-9
    from:
      kind: DockerImage
      name: quay.io/manuela/iot-anomaly-detection:0.3.2-9
    importPolicy: {}
    referencePolicy:
      type: Local
  - name: 0.3.2-10
    from:
      kind: DockerImage
      name: quay.io/manuela/iot-anomaly-detection:0.3.2-10
    importPolicy: {}
    referencePolicy:
      type: Local
  - name: 0.3.2-11
    from:
      kind: DockerImage
      name: quay.io/manuela/iot-anomaly-detection:0.3.2-11
    importPolicy: {}
    referencePolicy:
      type: Local
  - name: 0.3.2-12
    from:
      kind: DockerImage
      name: quay.io/manuela/iot-anomaly-detection:0.3.2-12
    importPolicy: {}
    referencePolicy:
      type: Local
  - name: 0.3.2-13
    from:
      kind: DockerImage
      name: quay.io/manuela/iot-anomaly-detection:0.3.2-13
    importPolicy: {}
    referencePolicy:
      type: Local
