apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: anomaly-detection
spec:
  tags:
  - name: 0.3.2-28
    from:
      kind: DockerImage
      name: quay.io/redhat-edge-computing/iot-anomaly-detection:0.3.2-28
    importPolicy: {}
    referencePolicy:
      type: Local
  - name: 0.3.2-29
    from:
      kind: DockerImage
      name: quay.io/redhat-edge-computing/iot-anomaly-detection:0.3.2-29
    importPolicy: {}
    referencePolicy:
      type: Local
  - name: 0.3.2-30
    from:
      kind: DockerImage
      name: quay.io/redhat-edge-computing/iot-anomaly-detection:0.3.2-30
    importPolicy: {}
    referencePolicy:
      type: Local
  - name: 0.3.2-31
    from:
      kind: DockerImage
      name: quay.io/redhat-edge-computing/iot-anomaly-detection:0.3.2-31
    importPolicy: {}
    referencePolicy:
      type: Local
  - name: 0.3.2-32
    from:
      kind: DockerImage
      name: quay.io/redhat-edge-computing/iot-anomaly-detection:0.3.2-32
    importPolicy: {}
    referencePolicy:
      type: Local
