apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: anomaly-detection
spec:
  tags:
  - name: 0.0.1-4
    from:
      kind: DockerImage
      name: quay.io/manuela/anomaly-detection:0.0.1-4
    importPolicy: {}
    referencePolicy:
      type: Local
  - name: 0.0.1-10
    from:
      kind: DockerImage
      name: quay.io/manuela/iot-anomaly-detection:0.0.1-10
    importPolicy: {}
    referencePolicy:
      type: Local
  - name: 0.0.1-11
    from:
      kind: DockerImage
      name: quay.io/manuela/iot-anomaly-detection:0.0.1-11
    importPolicy: {}
    referencePolicy:
      type: Local
  - name: 0.0.1-12
    from:
      kind: DockerImage
      name: quay.io/manuela/iot-anomaly-detection:0.0.1-12
    importPolicy: {}
    referencePolicy:
      type: Local
  - name: 0.0.1-14
    from:
      kind: DockerImage
      name: quay.io/manuela/iot-anomaly-detection:0.0.1-14
    importPolicy: {}
    referencePolicy:
      type: Local
  - name: 0.0.1-15
    from:
      kind: DockerImage
      name: quay.io/manuela/iot-anomaly-detection:0.0.1-15
    importPolicy: {}
    referencePolicy:
      type: Local
