apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: anomaly-detection
spec:
  tags:
  - name: 0.3.2-16
    from:
      kind: DockerImage
      name: quay.io/manuela/iot-anomaly-detection:0.3.2-16
    importPolicy: {}
    referencePolicy:
      type: Local
  - name: 0.3.2-17
    from:
      kind: DockerImage
      name: quay.io/manuela/iot-anomaly-detection:0.3.2-17
    importPolicy: {}
    referencePolicy:
      type: Local
  - name: 0.3.2-18
    from:
      kind: DockerImage
      name: quay.io/manuela/iot-anomaly-detection:0.3.2-18
    importPolicy: {}
    referencePolicy:
      type: Local
  - name: 0.3.2-19
    from:
      kind: DockerImage
      name: quay.io/manuela/iot-anomaly-detection:0.3.2-19
    importPolicy: {}
    referencePolicy:
      type: Local
  - name: 0.3.2-20
    from:
      kind: DockerImage
      name: quay.io/manuela/iot-anomaly-detection:0.3.2-20
    importPolicy: {}
    referencePolicy:
      type: Local
