apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: anomaly-detection
spec:
  tags:
  - name: 0.0.1-22
    from:
      kind: DockerImage
      name: quay.io/manuela/iot-anomaly-detection:0.0.1-22
    importPolicy: {}
    referencePolicy:
      type: Local
  - name: 0.0.1-23
    from:
      kind: DockerImage
      name: quay.io/manuela/iot-anomaly-detection:0.0.1-23
    importPolicy: {}
    referencePolicy:
      type: Local
  - name: 0.3.3-6
    from:
      kind: DockerImage
      name: quay.io/manuela/iot-anomaly-detection:0.3.3-6
    importPolicy: {}
    referencePolicy:
      type: Local
