apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: anomaly-detection
spec:
  tags:
  - name: 0.3.2-33
    from:
      kind: DockerImage
      name: quay.io/redhat-edge-computing/iot-anomaly-detection:0.3.2-33
    importPolicy: {}
    referencePolicy:
      type: Local
  - name: 0.3.2-34
    from:
      kind: DockerImage
      name: quay.io/dagger-refuse-cool/iot-anomaly-detection:0.3.2-34
    importPolicy: {}
    referencePolicy:
      type: Local
  - name: 0.3.2-35
    from:
      kind: DockerImage
      name: quay.io/claudiol/iot-anomaly-detection:0.3.2-35
    importPolicy: {}
    referencePolicy:
      type: Local
  - name: 0.3.2-36
    from:
      kind: DockerImage
      name: quay.io/claudiol/iot-anomaly-detection:0.3.2-36
    importPolicy: {}
    referencePolicy:
      type: Local
  - name: 0.3.2-37
    from:
      kind: DockerImage
      name: quay.io/claudiol/iot-anomaly-detection:0.3.2-37
    importPolicy: {}
    referencePolicy:
      type: Local
