apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../../manuela-openshift/anomaly-detection
patchesStrategicMerge:
- anomaly-detection-is.yaml
images:
- name: anomaly-detection
  newTag: 0.3.2-12
