apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    application: machine-sensor-2
    template: openjdk18-web-basic-s2i
    app.kubernetes.io/part-of: ManuELA
  name: machine-sensor-2
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      deploymentConfig: machine-sensor-2
  template:
    metadata:
      creationTimestamp: null
      labels:
        application: machine-sensor-2
        deploymentConfig: machine-sensor-2
      name: machine-sensor-2
    spec:
      containers:
      - name: machine-sensor
        image: machine-sensor:latest
        imagePullPolicy: Always
        ports:
          - containerPort: 8778
            name: jolokia
            protocol: TCP
          - containerPort: 8080
            name: http
            protocol: TCP
          - containerPort: 8443
            name: https
            protocol: TCP
        envFrom:
          - configMapRef: 
              name: machine-sensor-2
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File