apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: machine-sensor
  namespace: manuela-stormshift-machine-sensor
spec:
  lookupPolicy:
    local: true
  tags:
  - name: 0.3.1-20
    from:
      kind: DockerImage
      name: quay.io/ipbabble/iot-software-sensor:0.3.1-20
    importPolicy: {}
    referencePolicy:
      type: Local
  - name: 0.3.1-21
    from:
      kind: DockerImage
      name: quay.io/ipbabble/iot-software-sensor:0.3.1-21
    importPolicy: {}
    referencePolicy:
      type: Local
