apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: machine-sensor
  namespace: manuela-stormshift-machine-sensor
spec:
  lookupPolicy:
    local: true
  tags:
  - name: 0.3.1-105
    from:
      kind: DockerImage
      name: quay.io/martjack/iot-software-sensor:0.3.1-105
    importPolicy: {}
    referencePolicy:
      type: Local
