apiVersion: v1
kind: ConfigMap
metadata:
  name: machine-sensor-1
  namespace: manuela-stormshift-machine-sensor
data:
  MQTT_HOSTNAME: "broker-amq-mqtt-all-0-svc-rte-manuela-stormshift-messaging.{{ .Values.global.localClusterDomain }}"
  MQTT_PORT: "{{ .Values.machineSensor1.port }}"
  APP_NAME: "iot-sensor"
  DEVICE_ID: "pump-1"
  DEVICE_METRICS: "temperature,vibration,gps,light"
  MACHINE_ID: "floor-1-line-1-extruder-1"

  MQTT_TLSSNI: "false"
  MQTT_USER: "iotuser"

  SENSOR_GPS_ENABLED: "false"
  SENSOR_GPS_FINAL_LATITUDE: "40.689879"
  SENSOR_GPS_FINAL_LONGITUDE: "-73.992895"
  SENSOR_GPS_FREQUENCY: "5"
  SENSOR_GPS_INITIAL_LATITUDE: "42.579258"
  SENSOR_GPS_INITIAL_LONGITUDE: "-71.437841"
  SENSOR_GPS_ITERATION_LATITUDE: "-0.009"
  SENSOR_GPS_ITERATION_LONGITUDE: "-0.012"

  SENSOR_LIGHT_ENABLED: "false"
  SENSOR_LIGHT_FREQUENCY: "5"
  SENSOR_LIGHT_MAXITERATION: "3"
  SENSOR_LIGHT_MAXRANGE: "25000"
  SENSOR_LIGHT_MINITERATION: "0"
  SENSOR_LIGHT_MINRANGE: "0"
  SENSOR_LIGHT_START: "0"

  SENSOR_TEMPERATURE_ENABLED: "false"
  SENSOR_TEMPERATURE_FREQUENCY: "5"
  SENSOR_TEMPERATURE_MAXITERATION: "1"
  SENSOR_TEMPERATURE_MAXRANGE: "55"
  SENSOR_TEMPERATURE_MINITERATION: "0"
  SENSOR_TEMPERATURE_MINRANGE: "45"
  SENSOR_TEMPERATURE_STARTMAX: "50"
  SENSOR_TEMPERATURE_STARTMIN: "50"

  SENSOR_VIBRATION_ENABLED: "true"
  SENSOR_VIBRATION_FREQUENC: "5"
  SENSOR_VIBRATION_MAXITERATION: "1"
  SENSOR_VIBRATION_MAXRANGE: "18"
  SENSOR_VIBRATION_MINITERATION: "0"
  SENSOR_VIBRATION_MINRANGE: "10"
  SENSOR_VIBRATION_START: "15"
  SENSOR_VIBRATION_PEAKINTETVAL: "20"
