apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-to-s3-config
  namespace: manuela-data-lake
data:
  application.properties: |

    kafka.broker.uri={{ .Values.kafka.broker.uri }}
    kafka.broker.topic.temperature={{ .Values.kafka.broker.topic.temperature }}
    kafka.broker.topic.vibration={{ .Values.kafka.broker.topic.vibration }}

    s3.region={{ .Values.global.s3.bucket.region }}
    s3.bucket.name={{ .Values.global.s3.bucket.name }}
    s3.message.aggregation.count={{ .Values.global.s3.bucket.message.aggregation.count }}
    s3.custom.endpoint.enabled={{ .Values.global.s3.bucket.custom.endpoint.enabled }}
    # Convert this directory into a helm chart and use templating to set this
    s3.custom.endpoint.url={{ .Values.global.s3.bucket.custom.endpoint.url }}

