apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  generation: 1
  name: seldon-operator
spec:
  channel: alpha
  installPlanApproval: Manual
  name: seldon-operator
  source: community-operators
  sourceNamespace: openshift-marketplace
  startingCSV: seldon-operator.v1.2.1
