apiVersion: argoproj.io/v1alpha1
kind: ArgoCD
metadata:
  name: manuela-argocd
  namespace: manuela-ci
  labels:
    app.kubernetes.io/instance: manuela
spec:
  applicationInstanceLabelKey: argocd.argoproj.io/instance
  # Not the greatest way to pass git/quay info to sub-applications, but it will do until
  # we can support helmChart with kustomize
  # The other option is to pass them in as environment variables eg. BLUEPRINT_VERSION
  configManagementPlugins: "- name: kustomize-version\n  generate:\n    command: [sh,
    -c]\n    args: [\"kustomize version 1>&2 && exit 1\"]\n- name: kustomize-with-helm\n
    \ generate:\n    command: [\"kustomize\"]\n    args: [\"build\", \"--enable-helm\"]\n- name:
    helm-with-kustomize\n  init:\n    command: [\"/bin/sh\", \"-c\"]\n    args: [\"helm
    dependency build\"]\n  generate:\n    command: [sh, -c]\n    args: [\"helm template
    --release-name manuela-${BLUEPRINT_VERSION}
    --set global.quay.provider={{ .Values.global.quay.provider }}
    --set global.quay.account={{ .Values.global.quay.account }}
    --set global.git.provider={{ .Values.global.git.provider }}
    --set global.git.account={{ .Values.global.git.account }}
    --set global.git.username={{ .Values.global.git.username }}
    --set global.git.email={{ .Values.global.git.email }}
    --set global.git.target={{ .Values.global.git.target }}
    --set global.bpversion=${BLUEPRINT_VERSION} .
    --post-renderer ./kustomize\"]
    \ \n"
  controller:
    processors: {}
    resources:
      limits:
        cpu: "2"
        memory: 2Gi
      requests:
        cpu: 250m
        memory: 1Gi
  server:
    route:
      enabled: true
  grafana:
    enabled: false
  ha:
    enabled: false
  initialSSHKnownHosts: {}
  prometheus:
    enabled: false
  rbac:
    defaultPolicy: role:admin
  repo:
    image: quay.io/abeekhof/argocd
    version: v1.1.2-4.2
    resources:
      limits:
        cpu: "1"
        memory: 512Mi
      requests:
        cpu: 250m
        memory: 256Mi
