apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: manuela
  namespace: openshift-gitops
  labels:
    app.kubernetes.io/instance: manuela
spec:
  destination:
    name: in-cluster
    namespace: default
  project: default
  source:
    repoURL: https://{{ .Values.global.git.provider }}/{{ .Values.global.git.account }}/blueprints.git
    path: manufacturing-edge-ai-ml/charts/applications
    targetRevision: {{ .Values.global.git.target }}
    helm:
      releaseName: manuela-release-v1
      parameters:
      - name: global.git.provider
        value: {{ .Values.global.git.provider }}
      - name: global.git.account
        value: {{ .Values.global.git.account }}
      - name: global.git.target
        value: {{ .Values.global.git.target }}
      - name: global.git.email
        value: {{ .Values.global.git.email }}
