apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: build-and-test
spec:
  workspaces:
  - name: gitrepos
  - name: config
  - name: argocd-env-secret
  - name: build-artifacts
  params:
  - name: DEV_REVISION
    type: string
    default: {{ .Values.global.git.dev_revision }}
  - name: OPS_REVISION
    type: string
    default: {{ .Values.global.targetRevision }}
  tasks:
  - name: build-base-images
    taskRef:
      name: tkn
    params:
    - name: ARGS
      value:
      - pipeline
      - start
      - build-base-images
      - --param
      - PATH_CONTEXT=tekton/images/httpd-ionic
      - --param
      - DEV_REVISION=$(params.DEV_REVISION)
      - --param
      - OUTPUT_IMAGE_PROVIDER_CONFIGMAPKEY=IMAGE_PROVIDER
      - --param
      - OUTPUT_IMAGE_ACCOUNT_CONFIGMAPKEY=IMAGE_ACCOUNT
      - --param
      - OUTPUT_IMAGE_NAME=httpd-ionic
      - --workspace
      - name=gitrepos,claimName=gitrepos-rwo
      - --workspace
      - name=config,config=environment
      - --showlog
      - --nocolour

  - name: build-iot-anomaly-detection
    runAfter:
      - build-base-images
    taskRef:
      name: tkn
    params:
    - name: ARGS
      value:
      - pipeline
      - start
      - iot-component
      - --param
      - component_name=iot-anomaly-detection
      - --param
      - builder_image=quay.io/hybridcloudpatterns/python-38-rhel7
      - --param
      - output_image_name=anomaly-detection
      - --param
      - target_image_configmapkey=IOT_ANOMALY_IMAGE
      - --param
      - configmap_prefix=IOT_ANOMALY
      - --workspace
      - name=gitrepos,claimName=gitrepos-rwo
      - --workspace
      - name=config,config=environment
      - --workspace
      - name=build-artifacts,claimName=build-artifacts-rwo
      - --prefix-name
      - build-iot-anomaly-detection
      - --showlog
      - --nocolour
      - --exit-with-pipelinerun-error

  - name: build-iot-consumer
    runAfter:
      - build-iot-anomaly-detection
    taskRef:
      name: tkn
    params:
    - name: ARGS
      value:
      - pipeline
      - start
      - iot-component
      - --param
      - component_name=iot-consumer
      - --param
      - builder_image=registry.access.redhat.com/rhscl/nodejs-10-rhel7
      - --param
      - output_image_name=messaging
      - --param
      - target_image_configmapkey=IOT_CONSUMER_IMAGE
      - --param
      - configmap_prefix=IOT_CONSUMER
      - --workspace
      - name=gitrepos,claimName=gitrepos-rwo
      - --workspace
      - name=config,config=environment
      - --workspace
      - name=build-artifacts,claimName=build-artifacts-rwo
      - --prefix-name
      - build-iot-consumer
      - --showlog
      - --nocolour
      - --exit-with-pipelinerun-error

  - name: build-iot-frontend
    runAfter:
      - build-iot-consumer
    taskRef:
      name: tkn
    params:
    - name: ARGS
      value:
      - pipeline
      - start
      - iot-component
      - --param
      - component_name=iot-frontend
      - --param
      - builder_image=quay.io/hybridcloudpatterns/ubi8-s2i-web-app
      - --param
      - output_image_name=line-dashboard
      - --param
      - target_image_configmapkey=IOT_FRONTEND_IMAGE
      - --param
      - configmap_prefix=IOT_FRONTEND
      - --workspace
      - name=gitrepos,claimName=gitrepos-rwo
      - --workspace
      - name=config,config=environment
      - --workspace
      - name=build-artifacts,claimName=build-artifacts-rwo
      - --prefix-name
      - build-iot-frontend
      - --showlog
      - --nocolour
      - --exit-with-pipelinerun-error

  - name: build-iot-software-sensor
    runAfter:
      - build-iot-frontend
    taskRef:
      name: tkn
    params:
    - name: ARGS
      value:
      - pipeline
      - start
      - iot-component
      - --param
      - component_name=iot-software-sensor
      - --param
      - builder_image=registry.access.redhat.com/redhat-openjdk-18/openjdk18-openshift
      - --param
      - output_image_name=machine-sensor
      - --param
      - target_image_configmapkey=IOT_SWSENSOR_IMAGE
      - --param
      - configmap_prefix=IOT_SWSENSOR
      - --workspace
      - name=gitrepos,claimName=gitrepos-rwo
      - --workspace
      - name=config,config=environment
      - --workspace
      - name=build-artifacts,claimName=build-artifacts-rwo
      - --prefix-name
      - build-iot-software-sensor
      - --showlog
      - --nocolour
      - --exit-with-pipelinerun-error

  - name: argocd-sync-application
    taskRef:
      name: argocd-sync-and-wait
    runAfter:
    - build-iot-software-sensor
    workspaces:
    - name: argocd-env-secret
      workspace: argocd-env-secret
    params:
    - name: application-name
      #value: manuela-test-{{ .Values.global.pattern }}-{{ .Values.site.name }}
      value: manuela-test
    - name: flags
      value: --insecure
    - name: revision
      value: $(params.OPS_REVISION)
    - name: argocd-server
      # datacenter-gitops-server.industrial-edge-datacenter.svc
      value: "{{ .Values.clusterGroup.name }}-gitops-server.{{ .Values.global.pattern }}-{{ .Values.clusterGroup.name }}.svc"

  - name: test-all
    taskRef:
      name: tkn
    runAfter:
    - argocd-sync-application
    params:
    - name: ARGS
      value:
      - pipeline
      - start
      - test-all
      - --showlog
      - --nocolour

  - name: trigger-staging
    taskRef:
      name: tkn
    runAfter:
    - test-all
    params:
    - name: ARGS
      value:
      - pipeline
      - start
      - stage-production
      - --showlog
      - --nocolour
      - --param TAG=$(tasks.build-iot-consumer.bump-build-version-iot-consumer.results.image-tag)
      - --param CONFIGMAP_PREFIX=IOT_CONSUMER
      - --param SOURCE_IMAGE=image-registry.openshift-image-registry.svc:5000/manuela-tst-all/messaging

  - name: cleanup
    taskRef:
      name: cleanup
    runAfter:
    - trigger-staging
    workspaces:
    - name: gitrepos
      workspace: gitrepos
    - name: config
      workspace: config
    params:
    - name: subdirectory
      value: dev
    - name: COMPONENT_NAME
      value: iot-consumer
