apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-to-s3-config
data:
  application.properties: |
    
    kafka.broker.uri=manuela-kafka-cluster-kafka-bootstrap.manuela-data-lake-central-kafka-cluster.svc:9092
    kafka.broker.topic.temperature=manuela-factory.iot-sensor-sw-temperature
    kafka.broker.topic.vibration=manuela-factory.iot-sensor-sw-vibration

    s3.region=eu-central-1
    s3.bucket.name=manuela-data-lake
    s3.message.aggregation.count=10
    s3.custom.endpoint.enabled=true
    s3.custom.endpoint.url=s3-openshift-storage.apps.ocp4.stormshift.coe.muc.redhat.com

    