kind: Secret
apiVersion: v1
metadata:
  name: iot-kafka2s3-secret
type: Opaque  
data:
  application.properties: ICBzMy5hY2Nlc3NLZXk6IEN4ZkJCQlZGV1hEZGo1ek50MjZhCiAgczMuc2VjcmV0S2V5OiBjMXpNaVVJSnhJVjBMR3RyeXVDaTJEaDB2R0JtdUdtRzdNbE42YzdSCg==
