apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: manuela-tst-all
bases:
- ../../templates/manuela-team-rolebindings
- ../../templates/manuela-openshift/line-dashboard
- ../../templates/manuela-openshift/messaging
- ../../templates/manuela-openshift/messaging-kafka
- ../../templates/manuela-openshift/machine-sensor
# Comment out the following line if you don't want to run anomaly-detection (ODH)
- ../../templates/manuela-openshift/anomaly-detection
# - ../../templates/manuela-openshift/anomaly-detection
- ../../templates/installplan-approver
configMapGenerator:
- name: machine-sensor-1
  behavior: merge
  envs:
  - machine-sensor-1-configmap.properties
- name: machine-sensor-2
  behavior: merge
  envs:
  - machine-sensor-2-configmap.properties
- name: line-dashboard-configmap
  behavior: replace
  files:
  - config.json=line-dashboard-configmap-config.json
- name: messaging-configmap
  behavior: merge
  envs:
  - messaging-configmap.properties
patchesStrategicMerge:
- line-dashboard-route.yaml
- messaging-route.yaml
resources:
- manuela-tst-all-namespace.yaml
- manuela-tst-all-operatorgroup.yaml
- system-image-builder-role-binding.yaml
images:
- name: messaging
  newName: image-registry.openshift-image-registry.svc:5000/manuela-tst-all/messaging
  newTag: 0.3.2-50
- name: machine-sensor
  newName: image-registry.openshift-image-registry.svc:5000/manuela-tst-all/machine-sensor
  newTag: 0.3.1-32
- name: line-dashboard
  newName: image-registry.openshift-image-registry.svc:5000/manuela-tst-all/line-dashboard
  newTag: 0.3.1-57
- name: anomaly-detection
  newName: image-registry.openshift-image-registry.svc:5000/manuela-tst-all/anomaly-detection
  newTag: 0.3.2-34
