apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  generateName: manuela-tst-all-
  generation: 1
  name: manuela-tst-all
  namespace: manuela-tst-all
spec:
  targetNamespaces:
  - manuela-tst-all