global:
  datacenter:
    clustername: claudiol-dc1
    domain: blueprints.rhecoeng.com

  git:
    provider: github.com
    account: claudiol
    email: claudiol@redhat.com
    username: claudiol
    target: claudiol-experiment

messaging:
  vibrationAlert: true
  vibrationAnomaly: true 
  nodeTlsReject: 0

machineSensor1:
  port: 80

machineSensor2:
  port: 80
  sensorTemperature: false


