resources:
  - 00_advance-cluster-manager/00_namespace.yaml
  - 00_advance-cluster-manager/01_operator-group.yaml
  - 00_advance-cluster-manager/02_subscription.yaml
  - 00_advance-cluster-manager/04_multiclusterhub.yaml
  - 01_autoapprover/00_sa.yaml
  - 01_autoapprover/01_crb.yaml
  - 01_autoapprover/02_approver.yaml
  - 02_managed-clusters/baremetal-edge.yaml
  - 02_managed-clusters/staging-aws.yaml
  - 02_managed-clusters/staging-gcp.yaml
  - 06_opendatahub/subscription.yaml

bases:
  - 03_argocd/
  - 04_openshift-pipelines/
  - 05_manuela-ci/
  - 07_tekton/

