apiVersion: camel.apache.org/v1
kind: Integration
metadata:
  name: mqtt2kafka-integration
  namespace: manuela-stormshift-messaging
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  configuration:
    - type: configmap
      value: mqtt2kafka-config
  profile: OpenShift
  sources:
    - content: |
{{ .Files.Get "MQTT2KafkaRoute.java" | indent 8 }}
      name: MQTT2KafkaRoute.java
