apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../../manuela-openshift/machine-sensor
patchesStrategicMerge:
- machine-sensor-is.yaml
images:
- name: machine-sensor
  newTag: 0.3.1-17
