apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: machine-sensor
spec:
  tags:
  - name: 0.3.1-19
    from:
      kind: DockerImage
      name: quay.io/manuela/iot-software-sensor:0.3.1-19
    importPolicy: {}
    referencePolicy:
      type: Local
  - name: 0.3.1-20
    from:
      kind: DockerImage
      name: quay.io/manuela/iot-software-sensor:0.3.1-20
    importPolicy: {}
    referencePolicy:
      type: Local
  - name: 0.3.3-7
    from:
      kind: DockerImage
      name: quay.io/manuela/iot-software-sensor:0.3.3-7
    importPolicy: {}
    referencePolicy:
      type: Local
  - name: 0.3.2-1
    from:
      kind: DockerImage
      name: quay.io/manuela/iot-software-sensor:0.3.2-1
    importPolicy: {}
    referencePolicy:
      type: Local
  - name: 0.3.1-1
    from:
      kind: DockerImage
      name: quay.io/manuela/iot-software-sensor:0.3.1-1
    importPolicy: {}
    referencePolicy:
      type: Local
  - name: 0.3.1-1
    from:
      kind: DockerImage
      name: quay.io/manuela/iot-software-sensor:0.3.1-1
    importPolicy: {}
    referencePolicy:
      type: Local
  - name: 0.3.1-1
    from:
      kind: DockerImage
      name: quay.io/manuela/iot-software-sensor:0.3.1-1
    importPolicy: {}
    referencePolicy:
      type: Local
