apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: machine-sensor
spec:
  tags:
  - name: 0.3.1-28
    from:
      kind: DockerImage
      name: quay.io/redhat-edge-computing/iot-software-sensor:0.3.1-28
    importPolicy: {}
    referencePolicy:
      type: Local
  - name: 0.3.1-29
    from:
      kind: DockerImage
      name: quay.io/redhat-edge-computing/iot-software-sensor:0.3.1-29
    importPolicy: {}
    referencePolicy:
      type: Local
  - name: 0.3.1-30
    from:
      kind: DockerImage
      name: quay.io/redhat-edge-computing/iot-software-sensor:0.3.1-30
    importPolicy: {}
    referencePolicy:
      type: Local
  - name: 0.3.1-31
    from:
      kind: DockerImage
      name: quay.io/redhat-edge-computing/iot-software-sensor:0.3.1-31
    importPolicy: {}
    referencePolicy:
      type: Local
  - name: 0.3.1-32
    from:
      kind: DockerImage
      name: quay.io/redhat-edge-computing/iot-software-sensor:0.3.1-32
    importPolicy: {}
    referencePolicy:
      type: Local
  - name: 0.3.1-33
    from:
      kind: DockerImage
      name: quay.io/claudiol/iot-software-sensor:0.3.1-33
    importPolicy: {}
    referencePolicy:
      type: Local
  - name: 0.3.1-34
    from:
      kind: DockerImage
      name: quay.io/claudiol/iot-software-sensor:0.3.1-34
    importPolicy: {}
    referencePolicy:
      type: Local
