apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: machine-sensor
spec:
  tags:
  - name: 0.3.1-24
    from:
      kind: DockerImage
      name: quay.io/manuela/iot-software-sensor:0.3.1-24
    importPolicy: {}
    referencePolicy:
      type: Local
  - name: 0.3.1-25
    from:
      kind: DockerImage
      name: quay.io/manuela/iot-software-sensor:0.3.1-25
    importPolicy: {}
    referencePolicy:
      type: Local
  - name: 0.3.1-27
    from:
      kind: DockerImage
      name: quay.io/manuela/iot-software-sensor:0.3.1-27
    importPolicy: {}
    referencePolicy:
      type: Local
  - name: 0.3.1-28
    from:
      kind: DockerImage
      name: quay.io/manuela/iot-software-sensor:0.3.1-28
    importPolicy: {}
    referencePolicy:
      type: Local
  - name: 0.3.1-29
    from:
      kind: DockerImage
      name: quay.io/manuela/iot-software-sensor:0.3.1-29
    importPolicy: {}
    referencePolicy:
      type: Local
  - name: 0.3.1-30
    from:
      kind: DockerImage
      name: quay.io/manuela/iot-software-sensor:0.3.1-30
    importPolicy: {}
    referencePolicy:
      type: Local
  - name: 0.3.1-31
    from:
      kind: DockerImage
      name: quay.io/manuela/iot-software-sensor:0.3.1-31
    importPolicy: {}
    referencePolicy:
      type: Local
