apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: machine-sensor
spec:
  tags:
  - name: 0.3.1-14
    from:
      kind: DockerImage
      name: quay.io/manuela/iot-software-sensor:0.3.1-14
    importPolicy: {}
    referencePolicy:
      type: Local
  - name: 0.3.1-16
    from:
      kind: DockerImage
      name: quay.io/manuela/iot-software-sensor:0.3.1-16
    importPolicy: {}
    referencePolicy:
      type: Local
  - name: 0.3.1-17
    from:
      kind: DockerImage
      name: quay.io/manuela/iot-software-sensor:0.3.1-17
    importPolicy: {}
    referencePolicy:
      type: Local
  - name: 0.3.1-18
    from:
      kind: DockerImage
      name: quay.io/manuela/iot-software-sensor:0.3.1-18
    importPolicy: {}
    referencePolicy:
      type: Local
  - name: 0.3.1-19
    from:
      kind: DockerImage
      name: quay.io/manuela/iot-software-sensor:0.3.1-19
    importPolicy: {}
    referencePolicy:
      type: Local
  - name: 0.3.1-20
    from:
      kind: DockerImage
      name: quay.io/manuela/iot-software-sensor:0.3.1-20
    importPolicy: {}
    referencePolicy:
      type: Local
  - name: 0.3.3-4
    from:
      kind: DockerImage
      name: quay.io/manuela/iot-software-sensor:0.3.3-4
    importPolicy: {}
    referencePolicy:
      type: Local
