apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: machine-sensor
spec:
  tags:
  - name: 0.3.2-2
    from:
      kind: DockerImage
      name: quay.io/manuela/iot-software-sensor:0.3.2-2
    importPolicy: {}
    referencePolicy:
      type: Local
  - name: 0.3.2-1
    from:
      kind: DockerImage
      name: quay.io/manuela/iot-software-sensor:0.3.2-1
    importPolicy: {}
    referencePolicy:
      type: Local
  - name: 0.3.2-2
    from:
      kind: DockerImage
      name: quay.io/manuela/iot-software-sensor:0.3.2-2
    importPolicy: {}
    referencePolicy:
      type: Local
  - name: 0.3.1-1
    from:
      kind: DockerImage
      name: quay.io/manuela/iot-software-sensor:0.3.1-1
    importPolicy: {}
    referencePolicy:
      type: Local
  - name: 0.3.1-7
    from:
      kind: DockerImage
      name: quay.io/manuela/iot-software-sensor:0.3.1-7
    importPolicy: {}
    referencePolicy:
      type: Local
  - name: 0.3.1-8
    from:
      kind: DockerImage
      name: quay.io/manuela/iot-software-sensor:0.3.1-8
    importPolicy: {}
    referencePolicy:
      type: Local
  - name: 0.3.1-9
    from:
      kind: DockerImage
      name: quay.io/manuela/iot-software-sensor:0.3.1-9
    importPolicy: {}
    referencePolicy:
      type: Local
