apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: manuela-data-lake-central-kafka-cluster

resources:
- manuela-data-lake-central-kafka-cluster-namespace.yaml
- manuela-data-lake-central-kafka-cluster-operatorgroup.yaml
- amq-streams-operator-subscription.yaml
- kafka-cluster.yaml
- kafka-tls-certificate-and-key.yaml


bases:
- ../../../templates/manuela-team-rolebindings
  #- ../../../templates/installplan-approver
