apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: messaging
spec:
  tags:
  - name: 0.3.2-39
    from:
      kind: DockerImage
      name: quay.io/redhat-edge-computing/iot-consumer:0.3.2-39
    importPolicy: {}
    referencePolicy:
      type: Local
  - name: 0.3.2-40
    from:
      kind: DockerImage
      name: quay.io/redhat-edge-computing/iot-consumer:0.3.2-40
    importPolicy: {}
    referencePolicy:
      type: Local
  - name: 0.3.2-41
    from:
      kind: DockerImage
      name: quay.io/redhat-edge-computing/iot-consumer:0.3.2-41
    importPolicy: {}
    referencePolicy:
      type: Local
  - name: 0.3.2-42
    from:
      kind: DockerImage
      name: quay.io/redhat-edge-computing/iot-consumer:0.3.2-42
    importPolicy: {}
    referencePolicy:
      type: Local
  - name: 0.3.2-43
    from:
      kind: DockerImage
      name: quay.io/redhat-edge-computing/iot-consumer:0.3.2-43
    importPolicy: {}
    referencePolicy:
      type: Local
  - name: 0.3.2-46
    from:
      kind: DockerImage
      name: quay.io/redhat-edge-computing/iot-consumer:0.3.2-46
    importPolicy: {}
    referencePolicy:
      type: Local
  - name: 0.3.2-48
    from:
      kind: DockerImage
      name: quay.io/redhat-edge-computing/iot-consumer:0.3.2-48
    importPolicy: {}
    referencePolicy:
      type: Local
