apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: messaging
spec:
  tags:
  - name: 0.3.2-61
    from:
      kind: DockerImage
      name: quay.io/manuela/iot-consumer:0.3.2-61
    importPolicy: {}
    referencePolicy:
      type: Local
  - name: 0.3.2-62
    from:
      kind: DockerImage
      name: quay.io/manuela/iot-consumer:0.3.2-62
    importPolicy: {}
    referencePolicy:
      type: Local
  - name: 0.3.2-70
    from:
      kind: DockerImage
      name: quay.io/manuela/iot-consumer:0.3.2-70
    importPolicy: {}
    referencePolicy:
      type: Local
  - name: 0.3.2-71
    from:
      kind: DockerImage
      name: quay.io/manuela/iot-consumer:0.3.2-71
    importPolicy: {}
    referencePolicy:
      type: Local
  - name: 0.3.2-72
    from:
      kind: DockerImage
      name: quay.io/manuela/iot-consumer:0.3.2-72
    importPolicy: {}
    referencePolicy:
      type: Local
