apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: messaging
spec:
  tags:
  - name: 0.3.2-35
    from:
      kind: DockerImage
      name: quay.io/manuela/iot-consumer:0.3.2-35
    importPolicy: {}
    referencePolicy:
      type: Local
  - name: 0.3.2-36
    from:
      kind: DockerImage
      name: quay.io/manuela/iot-consumer:0.3.2-36
    importPolicy: {}
    referencePolicy:
      type: Local
  - name: 0.3.2-38
    from:
      kind: DockerImage
      name: quay.io/manuela/iot-consumer:0.3.2-38
    importPolicy: {}
    referencePolicy:
      type: Local
  - name: 0.3.2-39
    from:
      kind: DockerImage
      name: quay.io/manuela/iot-consumer:0.3.2-39
    importPolicy: {}
    referencePolicy:
      type: Local
  - name: 0.3.2-40
    from:
      kind: DockerImage
      name: quay.io/manuela/iot-consumer:0.3.2-40
    importPolicy: {}
    referencePolicy:
      type: Local
  - name: 0.3.2-41
    from:
      kind: DockerImage
      name: quay.io/manuela/iot-consumer:0.3.2-41
    importPolicy: {}
    referencePolicy:
      type: Local
  - name: 0.3.2-42
    from:
      kind: DockerImage
      name: quay.io/manuela/iot-consumer:0.3.2-42
    importPolicy: {}
    referencePolicy:
      type: Local
