apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: messaging
spec:
  tags:
  - name: 0.3.2-42
    annotations: null
    from:
      kind: DockerImage
      name: quay.io/manuela/iot-consumer:0.3.2-42
    importPolicy: {}
    referencePolicy:
      type: Local
  - name: 0.3.2-50
    from:
      kind: DockerImage
      name: quay.io/manuela/iot-consumer:0.3.2-50
    importPolicy: {}
    referencePolicy:
      type: Local
  - name: 0.3.2-51
    from:
      kind: DockerImage
      name: quay.io/manuela/iot-consumer:0.3.2-51
    importPolicy: {}
    referencePolicy:
      type: Local
  - name: 0.3.2-52
    from:
      kind: DockerImage
      name: quay.io/manuela/iot-consumer:0.3.2-52
    importPolicy: {}
    referencePolicy:
      type: Local
  - name: 0.3.2-53
    from:
      kind: DockerImage
      name: :0.3.2-53
    importPolicy: {}
    referencePolicy:
      type: Local
  - name: 0.3.2-58
    from:
      kind: DockerImage
      name: quay.io/manuela/iot-consumer:0.3.2-58
    importPolicy: {}
    referencePolicy:
      type: Local
  - name: 0.3.2-59
    from:
      kind: DockerImage
      name: quay.io/manuela/iot-consumer:0.3.2-59
    importPolicy: {}
    referencePolicy:
      type: Local
  - name: 0.3.2-60
    from:
      kind: DockerImage
      name: quay.io/manuela/iot-consumer:0.3.2-60
    importPolicy: {}
    referencePolicy:
      type: Local
