apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: messaging
spec:
  tags:
  - name: 0.3.2-24
    from:
      kind: DockerImage
      name: quay.io/manuela/iot-consumer:0.3.2-24
    importPolicy: {}
    referencePolicy:
      type: Local
  - name: 0.3.2-26
    from:
      kind: DockerImage
      name: quay.io/manuela/iot-consumer:0.3.2-26
    importPolicy: {}
    referencePolicy:
      type: Local
  - name: 0.3.2-27
    from:
      kind: DockerImage
      name: quay.io/manuela/iot-consumer:0.3.2-27
    importPolicy: {}
    referencePolicy:
      type: Local
  - name: 0.3.2-28
    from:
      kind: DockerImage
      name: quay.io/manuela/iot-consumer:0.3.2-28
    importPolicy: {}
    referencePolicy:
      type: Local
  - name: 0.3.2-29
    from:
      kind: DockerImage
      name: quay.io/manuela/iot-consumer:0.3.2-29
    importPolicy: {}
    referencePolicy:
      type: Local
  - name: 0.3.2-30
    from:
      kind: DockerImage
      name: quay.io/manuela/iot-consumer:0.3.2-30
    importPolicy: {}
    referencePolicy:
      type: Local
  - name: 0.3.2-32
    from:
      kind: DockerImage
      name: quay.io/manuela/iot-consumer:0.3.2-32
    importPolicy: {}
    referencePolicy:
      type: Local
