apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: messaging
spec:
  tags:
  - name: 0.3.2-13
    from:
      kind: DockerImage
      name: quay.io/manuela/iot-consumer:0.3.2-13
    importPolicy: {}
    referencePolicy:
      type: Local
  - name: 0.3.2-14
    from:
      kind: DockerImage
      name: quay.io/manuela/iot-consumer:0.3.2-14
    importPolicy: {}
    referencePolicy:
      type: Local
  - name: 0.3.2-15
    from:
      kind: DockerImage
      name: quay.io/manuela/iot-consumer:0.3.2-15
    importPolicy: {}
    referencePolicy:
      type: Local
  - name: 0.3.2-16
    from:
      kind: DockerImage
      name: quay.io/manuela/iot-consumer:0.3.2-16
    importPolicy: {}
    referencePolicy:
      type: Local
  - name: 0.3.2-17
    from:
      kind: DockerImage
      name: quay.io/manuela/iot-consumer:0.3.2-17
    importPolicy: {}
    referencePolicy:
      type: Local
  - name: 0.3.2-23
    from:
      kind: DockerImage
      name: quay.io/manuela/iot-consumer:0.3.2-23
    importPolicy: {}
    referencePolicy:
      type: Local
  - name: 0.3.2-24
    from:
      kind: DockerImage
      name: quay.io/manuela/iot-consumer:0.3.2-24
    importPolicy: {}
    referencePolicy:
      type: Local
