apiVersion: v1
kind: ConfigMap
metadata:
  name: messaging-configmap
data:
  MQTT_BROKER: 'ws://broker-amq-mqtt-all-0-svc:61616'
  MQTT_PASSWORD: iotuser
  MQTT_USER: iotuser
  PORT: '3000'
  SOCKET_PATH: /api/service-web/socket
  TEMPERATURE_THRESHOLD: '70.0'
  TOPIC_GPS: iot-sensor/sw/gps
  TOPIC_TEMPERATURE: iot-sensor/sw/temperature
  TOPIC_VIBRATION: iot-sensor/sw/vibration
  TOPIC_LIGHT: iot-sensor/sw/light

