apiVersion: apps/v1
kind: Deployment
metadata:
  name: pushprox-client
spec:
  template:
    spec:
      containers:
      - name: pushprox-client
        args: ["--metrics-addr", ":8080", "--proxy-url", "http://pushprox-proxy-manuela-argocd-aggregator.apps.claudiol-dc-test.blueprints.rhecoeng.com", "--fqdn=prometheus-operated.argocd.svc"]
