apiVersion: serving.kserve.io/v1alpha1
kind: ServingRuntime
metadata:
  annotations:
    opendatahub.io/accelerator-name: ''
    opendatahub.io/template-display-name: ML Server
    opendatahub.io/template-name: mlserver
    openshift.io/display-name: ML Server
  name: anomaly-detection-model-server
  namespace: ml-development
  labels:
    name: modelmesh-serving-mlserver-1.x-SR
    opendatahub.io/dashboard: 'true'
spec:
  supportedModelFormats:
    - autoSelect: true
      name: sklearn
      version: '0'
    - autoSelect: true
      name: xgboost
      version: '1'
    - autoSelect: true
      name: lightgbm
      version: '3'
  builtInAdapter:
    memBufferBytes: 134217728
    modelLoadingTimeoutMillis: 90000
    runtimeManagementPort: 8001
    serverType: mlserver
  multiModel: true
  containers:
    - env:
        - name: MLSERVER_MODELS_DIR
          value: /models/_mlserver_models/
        - name: MLSERVER_GRPC_PORT
          value: '8001'
        - name: MLSERVER_HTTP_PORT
          value: '8002'
        - name: MLSERVER_LOAD_MODELS_AT_STARTUP
          value: 'false'
        - name: MLSERVER_MODEL_NAME
          value: dummy-model-fixme
        - name: MLSERVER_HOST
          value: 127.0.0.1
        - name: MLSERVER_GRPC_MAX_MESSAGE_LENGTH
          value: '-1'
      image: 'docker.io/seldonio/mlserver:1.3.5'
      name: mlserver
      resources:
        limits:
          cpu: '2'
          memory: 8Gi
        requests:
          cpu: '1'
          memory: 4Gi
      volumeMounts:
        - mountPath: /dev/shm
          name: shm
  protocolVersions:
    - grpc-v2
  grpcEndpoint: 'port:8085'
  volumes:
    - emptyDir:
        medium: Memory
        sizeLimit: 2Gi
      name: shm
  replicas: 1
  tolerations: []
  grpcDataEndpoint: 'port:8001'
