---
apiVersion: "external-secrets.io/v1alpha1"
kind: ExternalSecret
metadata:
  name: s3-secret
  namespace: manuela-data-lake-central-s3-store
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: {{ .Values.secretStore.name }}
    kind: {{ .Values.secretStore.kind }}
  target:
    name: s3-secret
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        "application.properties": "{{ `{{ .s3Secret | base64decode | toString }}` }}"
  data:
    - secretKey: "s3Secret"
      remoteRef:
        key: {{ .Values.s3secret.key }}
        property: s3Secret
