apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: build-iot-software-sensor
objects:
- apiVersion: tekton.dev/v1beta1
  kind: PipelineRun
  metadata:
    generateName: build-and-test-iot-software-sensor-
  spec:
    pipelineRef:
      name: build-and-test
    workspaces:
    - name: config
      configMap:
        name: environment
    - name: argocd-env-secret
      secret:
        secretName: argocd-env
    - name: build-artifacts
      # persistentVolumeClaim:
      #   claimName: build-artifacts
      volumeClaimTemplate:
        spec:
          accessModes: 
          - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
    - name: gitrepos
      # persistentVolumeClaim:
      #   claimName: iot-software-sensor
      volumeClaimTemplate:
        spec:
          accessModes: 
          - ReadWriteOnce
          resources:
            requests:
              storage: 128Mi
    params:
    - name: S2I_BUILDER_IMAGE
      value: registry.access.redhat.com/redhat-openjdk-18/openjdk18-openshift
    - name: LOCAL_IMAGE
      value: image-registry.openshift-image-registry.svc:5000/manuela-tst-all/machine-sensor
    - name: PATH_CONTEXT
      value: components/iot-software-sensor
    - name: COMPONENT_NAME
      value: iot-swsensor
    - name: CONFIGMAP_PREFIX
      value: IOT_SWSENSOR
