apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: seed
objects:
- apiVersion: tekton.dev/v1beta1
  kind: PipelineRun
  metadata:
    generateName: seed-
  spec:
    pipelineRef:
      name: seed
    workspaces:
    - name: config
      configMap:
        name: environment
    - name: argocd-env-secret
      secret:
        secretName: argocd-env
    - name: build-artifacts
      # persistentVolumeClaim:
      #   claimName: build-artifacts
      volumeClaimTemplate:
        spec:
          accessModes:
          - ReadWriteMany
          resources:
            requests:
              storage: 1Gi
    - name: gitrepos
      # persistentVolumeClaim:
      #   claimName: iot-consumer
      volumeClaimTemplate:
        spec:
          accessModes:
          - ReadWriteMany
          resources:
            requests:
              storage: 1Gi

