apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: prometheus
spec:
  host: prometheus-manuela-argocd-aggregator.apps.edge-mgmt-hub.gcp.devcluster.openshift.com
  port:
    targetPort: web
  to:
    kind: Service
    name: prometheus-operated
    weight: 100
  wildcardPolicy: None