apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: messaging
spec:
  tags:
  - name: 0.3.2-69
    from:
      kind: DockerImage
      name: quay.io/claudiol/iot-consumer:0.3.2-69
    importPolicy: {}
    referencePolicy:
      type: Local
  - name: 0.3.2-72
    from:
      kind: DockerImage
      name: quay.io/martjack/iot-consumer:0.3.2-72
    importPolicy: {}
    referencePolicy:
      type: Local
  - name: 0.3.2-73
    from:
      kind: DockerImage
      name: quay.io/martjack/iot-consumer:0.3.2-73
    importPolicy: {}
    referencePolicy:
      type: Local
  - name: 0.3.2-74
    from:
      kind: DockerImage
      name: quay.io/martjack/iot-consumer:0.3.2-74
    importPolicy: {}
    referencePolicy:
      type: Local
  - name: 0.3.2-80
    from:
      kind: DockerImage
      name: quay.io/martjack/iot-consumer:0.3.2-80
    importPolicy: {}
    referencePolicy:
      type: Local
